name: Generate ASCII Artwork
on: [push]
jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repo
      uses: actions/checkout@v4
    - name: welcome message
      run: |
           echo "Welcome to GitHub Actions"
           ls -ltr
           cat README.md
    - name: Executing Script
      run: |
          chmod +x script.sh
          .github/workflows/script.sh
      
    
